[profile.default]
src = "src"
out = "out"
libs = ["lib"]
rpc_url = "https://bsc-dataseed.binance.org/"

[profile.dotenv]
path = ".env"

[rpc_endpoints]
mainnet = "https://bsc-dataseed.binance.org/"




[profile.dependencies]
OpenZeppelin = { git = "https://github.com/OpenZeppelin/openzeppelin-contracts.git", tag = "v5.0.2" }

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
